version: '3.8'

services:
  mysql:
    image: mysql:8
    container_name: mysql_test
    restart: always
    ports:
      - 3306:3306
    volumes:
      - ./init:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: Northwind
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    healthcheck:
      test: "echo '$MYSQL_USER'"
      interval: 5s
      timeout: 60s
      retries: 10

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    depends_on:
      mysql:
        condition: service_healthy