name: Test

env:
  MYSQL_ROOT_PASSWORD: ${{ secrets.MYSQL_ROOT_PASSWORD }}
  MYSQL_USER: ${{ secrets.MYSQL_USER }}
  MYSQL_PASSWORD: ${{ secrets.MYSQL_PASSWORD }}

on:
  push:
    branches:
      - "**"

jobs:
  mysql-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Start container
        run: |
          docker-compose up -d --build

      - name: Setup python and cache
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run pytest test
        run: |
          python -m pytest --html=report.html -v test/

      - name: Stop container
        if: always()
        run: |
          docker-compose down

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        if: always()
        with:
          name: artifact-with-test-results
          path: ${{ github.workspace }}/report.html